# SCN Redmine Compose
services:
  mariadb:
    image: docker.io/bitnamilegacy/mariadb:latest
    container_name: mariadb
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: on-failure:3
  redmine:
    build: .
    container_name: redmine
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
      - ./redmine-plugins:/opt/bitnami/redmine/plugins
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine
      - REDMINE_SMTP_HOST=smtp-relay.gmail.com
      - REDMINE_SMTP_PORT=587
      - REDMINE_SMTP_USER=redmine@seattlecommunitynetwork.org
      - REDMINE_SMTP_PASSWORD=${REDMINE_SMTP_PASSWORD}
      - REDMINE_IMAP_PASSWORD=${REDMINE_IMAP_PASSWORD}
      # for plugin support
      - BITNAMI_DEBUG=true
      - REDMINE_DATA_TO_PERSIST=/opt/bitnami/redmine/config/configuration.yml /opt/bitnami/redmine/config/database.yml files public/plugin_assets
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s
    restart: on-failure:3
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
